name: test
on:
  push:
    branches:
    - main
    paths-ignore:
    - 'README.md'
    - '.github/**'
  pull_request:
    paths-ignore:
    - 'README.md'
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x, 1.18.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: go mod tidy && make build
    - uses: dominikh/staticcheck-action@v1.2.0
      name: staticcheck
      with:
        install-go: false
    - name: Test
      run: make test